# Generated by Django 3.2.3 on 2021-06-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnergyEquitydotAI', '0003_modelthree'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelThree',
        ),
        migrations.DeleteModel(
            name='ModelTwo',
        ),
    ]
